### ISSUE TITLE
Error during build: System "waytemp" not found

### ISSUE THREAD

**Issue by sin-ack** [luciusmagn/waytemp#1]
Dramatis personae:
- OS: Gentoo Linux amd64
- SBCL version: 2.5.4

I've installed SBCL and added Quicklisp to my init file; however, when I try to run `make` I get:

```
sbcl --eval "(declaim (optimize (speed 3) (safety 3) (debug 3)))" --eval "(ql:quickload :waytemp)" --eval "(asdf:make :waytemp)" --quit
This is SBCL 2.5.4, an implementation of ANSI Common Lisp.
More information about SBCL is available at <http://www.sbcl.org/>.

SBCL is free software, provided as is, with absolutely no warranty.
It is mostly in the public domain; some portions are provided under
BSD-style licenses.  See the CREDITS and COPYING files in the
distribution for more information.

debugger invoked on a QUICKLISP-CLIENT:SYSTEM-NOT-FOUND in thread
#<THREAD tid=23529 "main thread" RUNNING {1203F781D3}>:
  System "waytemp" not found

Type HELP for debugger help, or (SB-EXT:EXIT) to exit from SBCL.

restarts (invokable by number or by possibly-abbreviated name):
  0: [CONTINUE               ] Try again
  1: [ABORT                  ] Give up on "waytemp"
  2: [REGISTER-LOCAL-PROJECTS] Register local projects and try again.
  3:                           Ignore runtime option --eval "(ql:quickload :waytemp)".
  4:                           Skip rest of --eval and --load options.
  5:                           Skip to toplevel READ/EVAL/PRINT loop.
  6: [EXIT                   ] Exit SBCL (calling #'EXIT, killing the process).

((LABELS QUICKLISP-CLIENT::RECURSE :IN QUICKLISP-CLIENT::COMPUTE-LOAD-STRATEGY) "waytemp")
   source: (CERROR "Try again" 'SYSTEM-NOT-FOUND :NAME NAME)
0]
```

What should I do?

**Comment by luciusmagn** [comment]
Yep! I forgot to do one of these two things:
- Add the local dir to the system search paths of quicklist/ASDF
- Tell people to clone into ~/quicklist/local-projects or ~/common-lisp (which are in the search paths)

I'll fix the build so it works from anywhere

**Comment by luciusmagn** [comment]
Fixed by https://github.com/luciusmagn/waytemp/commit/957f354a92b68a785eaa71bfe0511cb69db3bff5

**Comment by sin-ack** [comment]
Unfortunately I am still encountering this issue as of commit e4d5e2b.

**Comment by sin-ack** [comment]
Here's a reproducer Dockerfile:

```dockerfile
FROM gentoo/stage3

# HACK: Gentoo's SBCL package is currently broken so we have to fix the folder the SBCL core is installed to.
RUN emerge --sync \
 && getuto \
 && emerge --getbinpkg dev-vcs/git sbcl wayland-protocols wayland \
 && mv /usr/lib64/sbcl /usr/lib/sbcl \
 && git clone https://github.com/luciusmagn/waytemp /waytemp \
 && curl -O https://beta.quicklisp.org/quicklisp.lisp \
 && sbcl --load quicklisp.lisp --eval "(quicklisp-quickstart:install)"

WORKDIR /waytemp
```

Do:
- `docker build -t waytemp-reproducer -f reproducer.Dockerfile .`
- `docker run --rm -it waytemp-reproducer`

You will have to manually add Quicklisp to the init file unfortunately (couldn't figure out how to do that non-interactively):
```shell
$ sbcl
* (load "~/quicklisp/setup.lisp")
* (ql:add-to-init-file)
(press RET)
(exit)
```

 Then run `make` to see the error.

**Comment by luciusmagn** [comment]
Thank you, this helps a lot, hahaha

**Comment by luciusmagn** [comment]
Try now from the latest commit!

**Comment by sin-ack** [comment]
Works, cool!

**Comment by luciusmagn** [comment]
Awesome! Thank you!
